build:
	go-bindata -pkg handler -o handler/bindata.go assets/...
	go test ./...
	go build ./...

run:
	go-bindata -pkg handler -o handler/bindata.go assets/...
	go test ./...
	go build ./...
	go run main.go
